development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL") { "redis://localhost:6379/2" } %>
  channel_prefix: sandbox_playground_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_CABLE_URL") { "redis://localhost:6379/2" } %>
  channel_prefix: sandbox_playground_production
